### ISSUE TITLE
请求出现403是ip限制吗

### ISSUE THREAD

**Issue by zhangchengtest** [alipay/ams-java-sdk#2]
请求出现403是ip限制吗

**Comment by zhanggl** [comment]
嗨，请通过下述方式获取支持：


Alipay Merchant Service technical support
Address: overseas_support@service.alibaba.com
Working hour: 24 hours, Mon-Sun, GMT+8


https://global.alipay.com/docs/ac/general/getting-support

**Comment by hetianxia** [comment]
seriously? 007
